### ISSUE TITLE
Port over login / admin to app router

### ISSUE THREAD

**Issue by nkwsy** [nkwsy/Wildmile#142]
Allow permissions based on login / admin info. Stop users from editing a project / section without being approved.

**Comment by soleo** [comment]
It looks like I cannot avoid this to fix the authentication issue, gonna take this as well

**Comment by soleo** [comment]
This is now merged into CameraDeployment branch

**Comment by soleo** [comment]
The API for login/logout/reset-password etc is still in pages, but all the pages are in app router now. I think could close this issue if we are not looking to move the rest of them to app router yet
