### ISSUE TITLE
Allow for user to submit n number of plants

### ISSUE THREAD

**Issue by nkwsy** [nkwsy/Wildmile#16]
I know in our meeting I said that 5 would be enough. And it is, but it probably would be better if a person could just add a new plant type dynamically. 

So I think we should create the behavior where a user has one plant type option and can click a + to add another option. 

When a user loads a module with existing plants, the page could show N different plant species if the module already has N species on it. 

If this is too difficult to accomplish in a quick time period we can postpone until higher priority items are taken care of.

**Comment by charliegroll** [comment]
@nkwsy I can't remember if this was done, but I'm going to assign to you so you can either close or keep track for further work ✌️
