### ISSUE TITLE
Create Module details table page

### ISSUE THREAD

**Issue by nkwsy** [nkwsy/Wildmile#24]
Currently on modmap we have that table. I would like to create a page which has more info about each module, plant counts and other sortable features. This would allow a user to quantify plants, see module types, sort by area or tag and get insight. 

Peter, our plant guru, has requested the ability to see a running count of the number of individual plants per module and their species. I believe what we want to do is have the ability to sort by tags as well.

**Comment by charliegroll** [comment]
@nkwsy should this be closed?
